### PR TITLE
update for 3.10

### PR DESCRIPTION
**Pull request by derzw3rg**
- missing: everything except s8 support (as i only have that controller)
- phase meter (can't get it to work so far, maybe one other dev can check that one)

### CODE REVIEW

**Comment by derzw3rg** [comment]
looks like the stems waveform is broken right now. as soon as you switch between single deck/ multi deck view and back it works as expected (also for stem files loaded afterwards) as long as you don't load a non stem file. i have to investigate why.

**Comment by derzw3rg** [comment]
Hey @MrPatben8 as described i've encountered some problems.

1. some strange behavior with stem files: if you load a stem file into a deck the waveform is basicly invisible. you have to activate and deactivate the (show other deck) button (top right to the display) and then the waveforms show up
2. i only ported the s8 files as i don't own any of the other controllers

and i've got the phase meter to work by changing the import :)

**Comment by skymakai** [comment]
I'm very excited for this update... especially since we're now at version 3.11 which has native Apple Silicon support.  Thank you for your work.  LMK if you need help testing.

**Comment by skymakai** [comment]
Looks like ErikMinekus was able to get his mod updated.  Everything needed should be there.  I'll happily tip someone to get Kokernutz mod updated for 3.11.0 and Kontrol S5.  https://github.com/ErikMinekus/traktor-kontrol-screens/issues/26#issuecomment-1913333093

**Comment by ErikMinekus** [comment]
@derzw3rg I noticed the same issue with disappearing STEM waveforms, but it also happens on the default screens, even going back to Traktor 3.5.2. So it must be a Traktor issue.

Jorge Hontario also updated this mod last week, maybe you can compare notes: https://github.com/JorgeHontoria/traktor-kontrol-screens

**Comment by derzw3rg** [comment]
sorry for the late reply. as this is the first time i've touched qml it may be better if i close this pr if @JorgeHontoria did get it working

**Comment by skymakai** [comment]
Thanks guys!  I somehow did not see @JorgeHontoria's fork.  I'll follow his mod now.  Much thanks to @kokernutz for getting this going.

**Pull request closed without merging**
