### PR TITLE
Added MixerFX cycling for Kontrol S8

### PR DESCRIPTION
**Pull request by MrPatben8**
You can do so by pressing SHIFT… + FX arrow buttons on the respective channel.

If you are using 4 FX units then the filter must me ON in order for MixerFX selection, otherwise if the filter is OFF then pressing SHIFT + FX arrow buttons will route the channel to FX units 3 & 4 respectively.

### CODE REVIEW

**Comment by jkudish** [comment]
Hey there,

I tried your patch, and it works to cycle through the mixer FX; however, despite pressing shift + FX arrow, it still assigns FX Unit 2 to the channel, which is not the desired effect. I can workaround this by not having anything on in the FX unit, but it can get confusing.

Feel so close!

**Comment by MrPatben8** [comment]
Alright thanks! I'll take a look at that ASAP

**Comment by MrPatben8** [comment]
Alright, fixed the issue by removing `|| (fxMode.value == FxMode.TwoFxUnits)`
It should all be working now!

**Comment by MrPatben8** [comment]
You guys might like this. So the new Traktor S4 & S2 MK3 have a reverse button. Holding this down will temporarily activate Flux mode and begin to play the track in reverse. I did't see any way of controlling this on my S8 so I decided to add it. Simply press SHIFT + FLUX on the corresponding deck in order to activate Flux Reverse.

**Comment by jkudish** [comment]
Nice!

**Comment by MrPatben8** [comment]
@kokernutz Done, separate pull request is [here](https://github.com/kokernutz/traktor-kontrol-screens/pull/17)

**Comment by RixtarCorp** [comment]
Any news of when the conflicts will be resolved and the mixer effects for S8 will be merged? 

Thanks for all the great work!

**Comment by MrPatben8** [comment]
> Any news of when the conflicts will be resolved and the mixer effects for S8 will be merged?
> 
> Thanks for all the great work!
@RixtarCorp I'm not sure why those conflicts are present since those files are unmodified from the original, resolving the conflicts should be as easy as simply keeping the local changes, but that's up to @kokernutz.

**Comment by RixtarCorp** [comment]
@kokernutz Any chance we could get this merged? It would make me rather happy!

**Comment by skymakai** [comment]
Looks like some of these changes need to be updated for Traktor 3.2.

On the S5, Reverse works via Shift+Flux.

**Comment by skymakai** [comment]
Seems to also work when applied to the S5 Channel.qml.  

Only issue is S5 Screen doesn't show the FX Name; It shows "MFX1", "MFX2", etc, etc.

**Comment by skymakai** [comment]
Also found on the S5, the mixer effects selection button change state when holding shift, and do not show the proper state of on/off.

**Pull request closed without merging**
